# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1266, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_2 = QtWidgets.QFrame(self.frame_13)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.originalImage = ImageView(self.frame_2)
        self.originalImage.setObjectName("originalImage")
        self.verticalLayout_8.addWidget(self.originalImage)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.grayScaleImage = ImageView(self.frame_2)
        self.grayScaleImage.setObjectName("grayScaleImage")
        self.verticalLayout_9.addWidget(self.grayScaleImage)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.originalHistogram = PlotWidget(self.frame_2)
        self.originalHistogram.setObjectName("originalHistogram")
        self.verticalLayout_13.addWidget(self.originalHistogram)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_2)
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_11 = QtWidgets.QLabel(self.frame_16)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_15.addWidget(self.label_11, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_16)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.redChannel = ImageView(self.frame_14)
        self.redChannel.setObjectName("redChannel")
        self.verticalLayout_10.addWidget(self.redChannel)
        self.redHistogram = PlotWidget(self.frame_14)
        self.redHistogram.setObjectName("redHistogram")
        self.verticalLayout_10.addWidget(self.redHistogram)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.greenChannel = ImageView(self.frame_14)
        self.greenChannel.setObjectName("greenChannel")
        self.verticalLayout_11.addWidget(self.greenChannel)
        self.greenHistogram = PlotWidget(self.frame_14)
        self.greenHistogram.setObjectName("greenHistogram")
        self.verticalLayout_11.addWidget(self.greenHistogram)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.blueChannel = ImageView(self.frame_14)
        self.blueChannel.setObjectName("blueChannel")
        self.verticalLayout_12.addWidget(self.blueChannel)
        self.blueHistogram = PlotWidget(self.frame_14)
        self.blueHistogram.setObjectName("blueHistogram")
        self.verticalLayout_12.addWidget(self.blueHistogram)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.gridLayout_13.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_15)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.imageOne = ImageView(self.frame_15)
        self.imageOne.setObjectName("imageOne")
        self.verticalLayout_15.addWidget(self.imageOne)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.frame_15)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.imageTwo = ImageView(self.frame_15)
        self.imageTwo.setObjectName("imageTwo")
        self.verticalLayout_16.addWidget(self.imageTwo)
        self.horizontalLayout_6.addLayout(self.verticalLayout_16)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.frame_15)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.mixedImage = ImageView(self.frame_15)
        self.mixedImage.setObjectName("mixedImage")
        self.verticalLayout_14.addWidget(self.mixedImage)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.gridLayout_14.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_15)
        self.gridLayout_16.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.frame_12)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.noiseImage = ImageView(self.frame_4)
        self.noiseImage.setObjectName("noiseImage")
        self.verticalLayout.addWidget(self.noiseImage)
        self.frame_17 = QtWidgets.QFrame(self.frame_4)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.noiseOptions = QtWidgets.QComboBox(self.frame_17)
        self.noiseOptions.setObjectName("noiseOptions")
        self.noiseOptions.addItem("")
        self.noiseOptions.addItem("")
        self.noiseOptions.addItem("")
        self.horizontalLayout.addWidget(self.noiseOptions)
        self.noiseSlider = QtWidgets.QSlider(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noiseSlider.sizePolicy().hasHeightForWidth())
        self.noiseSlider.setSizePolicy(sizePolicy)
        self.noiseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.noiseSlider.setObjectName("noiseSlider")
        self.horizontalLayout.addWidget(self.noiseSlider)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_17)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.filteredImage = ImageView(self.frame_5)
        self.filteredImage.setObjectName("filteredImage")
        self.verticalLayout_2.addWidget(self.filteredImage)
        self.filtersOptions = QtWidgets.QComboBox(self.frame_5)
        self.filtersOptions.setObjectName("filtersOptions")
        self.filtersOptions.addItem("")
        self.filtersOptions.addItem("")
        self.filtersOptions.addItem("")
        self.verticalLayout_2.addWidget(self.filtersOptions)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.gridLayout_12.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.frame_12)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.edgeDetectionImage = ImageView(self.frame_7)
        self.edgeDetectionImage.setObjectName("edgeDetectionImage")
        self.verticalLayout_3.addWidget(self.edgeDetectionImage)
        self.edgeDetectionOptions = QtWidgets.QComboBox(self.frame_7)
        self.edgeDetectionOptions.setObjectName("edgeDetectionOptions")
        self.edgeDetectionOptions.addItem("")
        self.edgeDetectionOptions.addItem("")
        self.edgeDetectionOptions.addItem("")
        self.edgeDetectionOptions.addItem("")
        self.verticalLayout_3.addWidget(self.edgeDetectionOptions)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.freqeuncyFilteredImage = ImageView(self.frame_8)
        self.freqeuncyFilteredImage.setObjectName("freqeuncyFilteredImage")
        self.verticalLayout_4.addWidget(self.freqeuncyFilteredImage)
        self.frequancyFiltersOptions = QtWidgets.QComboBox(self.frame_8)
        self.frequancyFiltersOptions.setObjectName("frequancyFiltersOptions")
        self.frequancyFiltersOptions.addItem("")
        self.frequancyFiltersOptions.addItem("")
        self.verticalLayout_4.addWidget(self.frequancyFiltersOptions)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.frame_9 = QtWidgets.QFrame(self.frame_12)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.equalizedImage = ImageView(self.frame_10)
        self.equalizedImage.setObjectName("equalizedImage")
        self.verticalLayout_5.addWidget(self.equalizedImage)
        self.gridLayout_10.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.normalizedImage = ImageView(self.frame_11)
        self.normalizedImage.setObjectName("normalizedImage")
        self.verticalLayout_6.addWidget(self.normalizedImage)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.gridLayout_17.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_12)
        self.gridLayout_18.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1266, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Original Image"))
        self.label_8.setText(_translate("MainWindow", "Gray Scale Image"))
        self.label_9.setText(_translate("MainWindow", "Histogram"))
        self.label_11.setText(_translate("MainWindow", "Channels"))
        self.label_12.setText(_translate("MainWindow", "Image 1"))
        self.label_13.setText(_translate("MainWindow", "Mixed Image"))
        self.label_10.setText(_translate("MainWindow", "Mixed Image"))
        self.label.setText(_translate("MainWindow", "Noisy Image"))
        self.noiseOptions.setItemText(0, _translate("MainWindow", "Uniform"))
        self.noiseOptions.setItemText(1, _translate("MainWindow", "Guassian"))
        self.noiseOptions.setItemText(2, _translate("MainWindow", "Salt & Pepper"))
        self.label_2.setText(_translate("MainWindow", "Filtered Image"))
        self.filtersOptions.setItemText(0, _translate("MainWindow", "Average"))
        self.filtersOptions.setItemText(1, _translate("MainWindow", "Guassian"))
        self.filtersOptions.setItemText(2, _translate("MainWindow", "Median"))
        self.label_3.setText(_translate("MainWindow", "Image Edges"))
        self.edgeDetectionOptions.setItemText(0, _translate("MainWindow", "Sobel"))
        self.edgeDetectionOptions.setItemText(1, _translate("MainWindow", "Roberts"))
        self.edgeDetectionOptions.setItemText(2, _translate("MainWindow", "Prewitt"))
        self.edgeDetectionOptions.setItemText(3, _translate("MainWindow", "Canny"))
        self.label_4.setText(_translate("MainWindow", "Frequancy Filters"))
        self.frequancyFiltersOptions.setItemText(0, _translate("MainWindow", "LPF"))
        self.frequancyFiltersOptions.setItemText(1, _translate("MainWindow", "HPF"))
        self.label_5.setText(_translate("MainWindow", "Eqaulized Image"))
        self.label_6.setText(_translate("MainWindow", "Normalized Image"))
from pyqtgraph import ImageView, PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
